sonar.projectKey=blog-pessoal-dotnet
sonar.working.directory=C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal
sonar.pullrequest.cache.basepath=C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal

20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.projectKey=blog-pessoal-dotnet:20B98393-43A4-E386-15FF-47545BD6C5B5
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.projectName=BlogPessoal
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.projectBaseDir=C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.sourceEncoding=utf-8
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.tests=
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.sources=\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Controllers\\IA\\IAController.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Controllers\\PostagemController.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Controllers\\TemaController.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Controllers\\UsuarioController.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Data\\AppDbContext.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\DTOs\\PostagemRequestDTO.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\DTOs\\PostagemResponseDTO.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\DTOs\\ResultadoIA.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\DTOs\\UsuarioRequest.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\DTOs\\UsuarioResponseDTO.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Migrations\\20260519112909_IniciandoBancoDeDados.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Migrations\\20260519112909_IniciandoBancoDeDados.Designer.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Migrations\\20260522182942_AddRequiredFields.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Migrations\\20260522182942_AddRequiredFields.Designer.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Migrations\\AppDbContextModelSnapshot.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Models\\Postagem.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Models\\Tema.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Models\\Usuario.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Models\\UsuarioLogin.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Program.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Repositories\\IPostagemRepository.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Repositories\\ITemaRepository.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Repositories\\IUsuarioRepository.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Repositories\\PostagemRepository.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Repositories\\TemaRepository.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Repositories\\UsuarioRepository.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Services\\IA\\GeminiService.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Services\\IA\\IIAServices.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Services\\IA\\PromptBuild.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Services\\IPostagemService.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Services\\ITemaServices.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Services\\IUsuarioServices.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Services\\JwtService.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Services\\PostagemService.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Services\\TemaService.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Services\\UsuarioService.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\BlogPessoal.GlobalUsings.g.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\BlogPessoal.AssemblyInfo.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\BlogPessoal.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\appsettings.Development.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\appsettings.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\.gitignore",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\BlogPessoal.http",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\Properties\\launchSettings.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\BlogPessoal.csproj.nuget.dgspec.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\project.assets.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\BlogPessoal.deps.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\BlogPessoal.runtimeconfig.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\BlogPessoal.staticwebassets.endpoints.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\BlogPessoal.sourcelink.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\BuildHost-net472\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json",\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json"

20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\0"
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\0\\Issues.json"
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.cs.scanner.telemetry=\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\0\\Telemetry.json"

20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.working.directory=C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\.sonar\\mod0
5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7.sonar.projectKey=blog-pessoal-dotnet:5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7
5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7.sonar.projectName=BlogPessoal.Tests
5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7.sonar.projectBaseDir=C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal.Tests
5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7.sonar.sourceEncoding=utf-8
5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7.sonar.sources=
5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7.sonar.tests=\


5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\1"
5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\1\\Issues.json"
5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7.sonar.cs.scanner.telemetry=\
"C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\1\\Telemetry.json"

5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7.sonar.working.directory=C:\\Users\\mauri\\OneDrive\\Documentos\\GitHub\\Acelera-Maker\\Projeto Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=20B98393-43A4-E386-15FF-47545BD6C5B5,5456AFE7-DF0D-0B5D-6554-32DA9F8CEAC7

