// <auto-generated />
using System;
using BlogPessoal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogPessoal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519112909_IniciandoBancoDeDados")]
    partial class IniciandoBancoDeDados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlogPessoal.Models.Postagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoriaIA")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResumoIA")
                        .HasColumnType("longtext");

                    b.Property<string>("TagsIA")
                        .HasColumnType("longtext");

                    b.Property<long?>("TemaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Texto")
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tb_postagens");
                });

            modelBuilder.Entity("BlogPessoal.Models.Tema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("tb_temas");
                });

            modelBuilder.Entity("BlogPessoal.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Foto")
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Senha")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("tb_usuarios");
                });

            modelBuilder.Entity("BlogPessoal.Models.Postagem", b =>
                {
                    b.HasOne("BlogPessoal.Models.Tema", "Tema")
                        .WithMany("Postagem")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BlogPessoal.Models.Usuario", "Usuario")
                        .WithMany("Postagem")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tema");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BlogPessoal.Models.Tema", b =>
                {
                    b.Navigation("Postagem");
                });

            modelBuilder.Entity("BlogPessoal.Models.Usuario", b =>
                {
                    b.Navigation("Postagem");
                });
#pragma warning restore 612, 618
        }
    }
}
